name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build --tag bombsquad-server:ci .
